FROM ubuntu/nginx:1.18-20.04_edge
RUN mkdir /home/app
WORKDIR /home/app
USER root
COPY ./server/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./server/hello_fcgi.c /home/app/hello_fcgi.c
COPY ./server/start.sh /home/app/start.sh
RUN apt-get update; \
    apt-get install -y gcc spawn-fcgi libfcgi-dev; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*; \
    chown -R nginx:nginx /etc/nginx/nginx.conf; \
    chown -R nginx:nginx /var/log/nginx; \
    chown -R nginx:nginx /var/lib/nginx; \
    chown -R nginx:nginx /var/cache/nginx; \
    chown -R nginx:nginx /home/app; \
    touch /var/run/nginx.pid; \
    chown -R nginx:nginx /var/run/nginx.pid; \
    chmod +x start.sh; \
    chmod u-s /usr/bin/passwd; \
    chmod u-s /usr/bin/newgrp; \
    chmod g-s /usr/bin/chage; \
    chmod u-s /usr/bin/gpasswd; \
    chmod u-s /bin/su; \
    chmod u-s /bin/mount; \
    chmod g-s /usr/bin/wall; \
    chmod u-s /usr/bin/chsh; \
    chmod g-s /usr/bin/expiry; \
    chmod u-s /usr/bin/chfn; \
    chmod u-s /bin/umount; \
    chmod g-s /sbin/unix_chkpwd;
HEALTHCHECK --interval=30s --timeout=3s CMD curl --fail http://localhost || exit 1
ENTRYPOINT ["./start.sh"]
USER nginx
