services:
  app:
    image: nginx:task5
    
    networks:
      - appnet

  proxy:
    image: ubuntu/nginx:1.18-20.04_edge
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
    ports:
      - "80:8080"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge